app_config:
  app_port: 8080
  write_timeout: 20 # temporary value
  read_time_out: 20 # temporary value
  idle_timeout: 20 # temporary value
square_config:
  base_url: "https://connect.squareup.com/v2"


